### PR TITLE
Trying to fix `share` action

### PR DESCRIPTION
**Pull request by jeffque**
It added `<br>` where it shouldn't be. Trying to asks for a `\n` in hope it helps

### CODE REVIEW

**Comment by jeffque** [comment]
Test post on bsky: https://bsky.app/profile/jeffquesado.ulivre.dev/post/3la5bm5jxn32y

Test setup:

Inspect page, select the share element (I added in the DOM an ID to the element), alter the `href` as this:

```js
const shareable = document.getElementById('shareable') // the id added in the DOM directly
const data = {
  category: {
    title: "Marmota marmotosa"
  },
  handle: "jeffquesado.ulivre.dev"
}

shareable.href = "https://bsky.app/intent/compose?text=" +   
  encodeURI(`I'm __${data.category?.title}__ on 🦋\n\nCheck it out: https://jyc.dev/at/${data.handle}\n\n🫵 Get in, and claim your digital beast too 🐾 ! ?\n\n👀 @jyc.dev `)
```

**Comment by jeffque** [comment]
The preview isn't good, but at least it worked 👀

the preview of the share click. It does not show the newline tho

**Comment by jeffque** [comment]
Also about the share preview: it seems that you were not tagged, but indeed it tags when posting

**Comment by jycouet** [comment]
Hoooo, sorry I didn't check mail & GitHub!!!

On what browser are you?
For me `\n` didn't work, but `<br>` did.

**Comment by jeffque** [comment]
> Hoooo, sorry I didn't check mail & GitHub!!!
> 
> 
> 
> On what browser are you?
> 
> For me `\n` didn't work, but `<br>` did. 

Firefox on MacBook.

Perhaps it is something browser specific? Maybe when Firefox is submitting the form it sends the `<br>` tags to bsky backend instead of something the server recognizes as new line?

**Comment by jycouet** [comment]
Let's merge this ;)

**Pull request merged**
